// An enterprise product team, written as statements. Compare the dairy farm,
// whose layout, clicks and story are authored by hand: here only what things
// are, how they relate, and why they exist is written down. derive() works out
// the rest.

import { derive } from '../../scene/derive'

export const software = derive({
  id: 'software',
  title: 'Product team',
  goal: 'deliver software customers rely on',
  who: 'the team',
  intro:
    'A product team, as a black box. Requests and guidance go in, features and a running service come out. So do bugs that escape, and debt that piles up quietly, and things nobody can name yet.',
  inside:
    'Inside, requests become cards, cards cross the board, code is built and reviewed, and the test pipeline sends what it catches back to the backlog. Inside the boundary a bug is work. Past the release it’s an incident with a customer’s name on it.',
  outro:
    'Each part of this machine can answer one question: what are you here for? And each answer leaves something behind. That residue is the next problem.',

  nodes: [
    {
      id: 'team',
      kind: 'system',
      label: 'Product team',
      note: 'turns needs into running software',
      why: 'The team exists to turn what customers need into software they can rely on. Everything on this canvas, the board, the gates, the targets, is there because of that, or because of something that was.',
    },

    // Inputs
    { id: 'requests', kind: 'source', label: 'Customer requests', parent: 'team', relation: 'input to', why: 'Requests arrive from customers, sales and support, more of them than any team can build. Choosing among them is the first thing the team does.' },
    { id: 'guidance', kind: 'source', label: 'Product guidance', aka: ['product management', 'product managers'], parent: 'team', relation: 'input to', why: 'Product management sits outside the team and guides its product owners: what matters, for whom, by when. It arrives as priorities, and sometimes as dates.' },
    { id: 'people', kind: 'source', label: 'Engineers’ time', aka: ['engineers', 'developers'], parent: 'team', relation: 'input to', why: 'The one input that can’t be bought faster. Every other choice here is about spending it.' },
    { id: 'tools', kind: 'source', label: 'Cloud & tooling', aka: ['cloud', 'tooling'], parent: 'team', relation: 'input to', why: 'Servers, pipelines and licences. Rented by the hour, so they show up on a bill instead of a board.' },
    { id: 'libs', kind: 'source', label: 'Open-source libraries', aka: ['libraries', 'dependencies', 'open source'], parent: 'team', relation: 'input to', why: 'Most of the running code was written by strangers, for free. It ages on their schedule, not the team’s.' },

    // Outputs
    { id: 'features', kind: 'sink', label: 'Features', valence: 'desired', parent: 'team', relation: 'output of', why: 'What customers asked for, shipped. It’s what the roadmap counts.' },
    { id: 'service', kind: 'sink', label: 'Running service', valence: 'desired', aka: ['uptime', 'operations'], parent: 'team', relation: 'output of', why: 'Software only helps while it runs. Keeping it running is half the work and almost none of the roadmap.' },
    { id: 'bugs', kind: 'sink', label: 'Escaped bugs', valence: 'undesired', aka: ['bugs', 'defects', 'incidents'], parent: 'team', relation: 'output of', why: 'Every team ships bugs. The ones caught inside become cards; the ones that escape become a customer’s bad day.' },
    { id: 'debt', kind: 'sink', label: 'Technical debt', note: 'diffuse', valence: 'undesired', diffuse: true, aka: ['debt', 'tech debt'], parent: 'team', relation: 'output of', why: 'Every shortcut is a loan against future work. It leaves no single trace, just a team that gets a little slower every quarter.' },
    { id: 'unknown', kind: 'sink', label: '?', valence: 'unknown', parent: 'team', relation: 'output of', why: 'Every system has outputs nobody can name at design time. The question mark is honest about it.' },

    // Inside
    { id: 'backlog', kind: 'part', label: 'Backlog', parent: 'team', relation: 'part of', why: 'Where requests, guidance and caught bugs queue up as cards. The product owner orders it; the order is the strategy.' },
    { id: 'board', kind: 'part', label: 'Sprint board', aka: ['scrum', 'kanban', 'sprint'], parent: 'team', relation: 'part of', why: 'Scrum or kanban, the board makes work visible: what’s being done, what’s stuck, what’s next.' },
    { id: 'build', kind: 'part', label: 'Build & review', aka: ['code review', 'review'], parent: 'team', relation: 'part of', why: 'Engineers turn cards into code and check each other’s. Where the time goes, and where shortcuts get taken.' },
    { id: 'tests', kind: 'part', label: 'Test pipeline', aka: ['pipeline', 'ci'], parent: 'team', relation: 'part of', why: 'Every change runs the tests. What fails goes back to the backlog: a bug caught inside is just another card.' },
    { id: 'release', kind: 'part', label: 'Release', parent: 'team', relation: 'part of', why: 'The boundary that matters: before it, a bug costs the team; after it, the customer.' },
    { id: 'ops', kind: 'part', label: 'Operations', aka: ['on call'], parent: 'team', relation: 'part of', why: 'Someone watches the service at three in the morning. Their pager is where escaped bugs come home.' },

    // Branch: bugs caught outside
    {
      id: 'pBugs',
      kind: 'problem',
      label: 'Customers find bugs',
      note: 'caught outside, not in',
      parent: 'bugs',
      relation: 'arises from',
      ask: 'What if customers find the bugs?',
      says: 'Escaped bugs become a problem the day a customer finds one first. The obvious answer is a gate: QA signs off every release. Fewer bugs get out. Releases slow down, and quality quietly becomes someone else’s job.',
      why: 'A bug the pipeline catches is a card. A bug a customer catches is an escalation, a hotfix and a dent in trust.',
    },
    {
      id: 'qaGate',
      kind: 'solution',
      label: 'QA sign-off',
      strategy: 'contain',
      by: 'the QA department',
      parent: 'pBugs',
      relation: 'solves',
      says: 'A QA gate again: contain the bugs at the release, at the cost of speed and of who owns quality.',
      why: 'A QA department tests each release before it goes out: contain the bugs at the boundary. It works, and it moves the boundary.',
    },
    { id: 'qaDept', kind: 'source', label: 'QA department', aka: ['testers', 'qa'], parent: 'qaGate', relation: 'needed by', why: 'The gate needs people behind it: testers outside the team, with their own queue and their own manager.' },
    { id: 'fewerBugs', kind: 'sink', label: 'Fewer escaped bugs', valence: 'desired', parent: 'qaGate', relation: 'output of', why: 'The gate catches what the team missed. Fewer bugs reach customers.' },
    { id: 'slower', kind: 'sink', label: 'Slower releases', valence: 'undesired', parent: 'qaGate', relation: 'output of', why: 'Every release waits its turn in QA’s queue. Changes pile up, so each release is bigger, and riskier.' },
    { id: 'qaJob', kind: 'sink', label: 'Quality becomes QA’s job', note: 'diffuse', valence: 'undesired', diffuse: true, parent: 'qaGate', relation: 'output of', why: 'With a gate behind them, developers test less. The gate works, so it’s needed more: shifting the burden.' },
    { id: 'qUnknown', kind: 'sink', label: '?', valence: 'unknown', parent: 'qaGate', relation: 'output of', why: 'What a separate QA department does to the team, over years, nobody can fully say.' },
    {
      id: 'shiftLeft',
      kind: 'solution',
      label: 'Tests in pipeline',
      strategy: 'eliminate',
      by: 'the team',
      parent: 'pBugs',
      relation: 'solves',
      aka: ['shift left', 'automated tests', 'test automation'],
      says: 'Tests in the pipeline instead: catch bugs at the commit, inside the boundary, where they’re only work. The price is tests to maintain, and the ones that fail at random.',
      why: 'The team writes tests that run on every change: eliminate escapes at the source by catching bugs where they’re cheap.',
    },
    { id: 'atCommit', kind: 'sink', label: 'Bugs caught at commit', valence: 'desired', parent: 'shiftLeft', relation: 'output of', why: 'A bug caught minutes after it’s written costs minutes. The customer never meets it.' },
    { id: 'upkeep', kind: 'sink', label: 'Test upkeep', valence: 'undesired', parent: 'shiftLeft', relation: 'output of', why: 'Tests are code too. Every feature now comes with tests to write and keep up to date.' },
    { id: 'flaky', kind: 'sink', label: 'Flaky tests', valence: 'undesired', parent: 'shiftLeft', relation: 'output of', why: 'Some tests fail at random. Once people learn to rerun until green, the pipeline stops meaning anything.' },
    { id: 'sUnknown', kind: 'sink', label: '?', valence: 'unknown', parent: 'shiftLeft', relation: 'output of', why: 'What a pipeline teaches a team to ignore, nobody knows yet.' },

    // Branch: the roadmap date
    { id: 'comp', kind: 'context', label: 'Competitor’s launch', aka: ['competitor', 'competitors', 'competition'], why: 'A competitor shipped first. That’s product management’s problem, not the team’s, until a date brings it inside.' },
    {
      id: 'roadmap',
      kind: 'rule',
      label: 'Roadmap date: Q3',
      aka: ['roadmap', 'deadline', 'date'],
      parent: 'comp',
      relation: 'product management’s answer to',
      why: 'The date is someone else’s solution. For product management it answers a competitor; for the team it is a new problem, made on purpose.',
    },
    {
      id: 'pDate',
      kind: 'problem',
      label: 'Too much for Q3',
      note: 'made a problem by a date',
      parent: 'features',
      pressedBy: 'roadmap',
      relation: 'arises from',
      ask: 'What does a roadmap date do?',
      says: 'A date arrives. It’s product management’s answer to a competitor, and here it lands as a problem, on purpose: the scope won’t fit. Cutting scope meets the date with less, and breaks promises somebody already made upstream.',
      why: 'Features were always slow to come. The date is what makes too few of them a problem by Q3.',
    },
    {
      id: 'cutScope',
      kind: 'solution',
      label: 'Cut the scope',
      strategy: 'accept',
      by: 'the product owner',
      parent: 'pDate',
      relation: 'solves',
      aka: ['scope'],
      why: 'The product owner keeps the date and drops what won’t fit. Honest, and someone upstream has to hear it.',
    },
    { id: 'smaller', kind: 'sink', label: 'Date met, smaller', valence: 'desired', parent: 'cutScope', relation: 'output of', why: 'Q3 is met, with less in it. What shipped works.' },
    { id: 'promises', kind: 'sink', label: 'Promises broken upstream', valence: 'undesired', parent: 'cutScope', relation: 'output of', why: 'Product management sold the full scope already. The cut lands on their credibility, with customers and with sales.' },
    { id: 'cUnknown', kind: 'sink', label: '?', valence: 'unknown', parent: 'cutScope', relation: 'output of', why: 'What dropped scope does to next quarter’s roadmap, nobody can say yet.' },
    {
      id: 'cutCorners',
      kind: 'solution',
      label: 'Skip the tests',
      strategy: 'shift',
      by: 'the team',
      parent: 'pDate',
      relation: 'solves',
      aka: ['cut corners', 'shortcuts', 'crunch'],
      says: 'Or keep the full scope and skip the tests. The date is met in full, and the cost moves: into debt, and into the bugs customers will find. That’s the first branch again, fed from here.',
      why: 'The team keeps the scope and the date by not testing. The problem doesn’t go away; it moves somewhere slower.',
    },
    { id: 'inFull', kind: 'sink', label: 'Date met in full', valence: 'desired', parent: 'cutCorners', relation: 'output of', why: 'Everything promised, by Q3. On the roadmap, it looks like a win.' },
    { id: 'moreDebt', kind: 'sink', label: 'More debt', note: 'diffuse', valence: 'undesired', diffuse: true, parent: 'cutCorners', relation: 'output of', why: 'Untested code is code nobody dares to change. Next quarter starts slower.' },
    { id: 'moreBugs', kind: 'sink', label: 'More escaped bugs', valence: 'undesired', parent: 'cutCorners', relation: 'output of', why: 'What wasn’t tested gets tested by customers. It feeds straight back into the first problem: customers find the bugs.' },
    { id: 'kUnknown', kind: 'sink', label: '?', valence: 'unknown', parent: 'cutCorners', relation: 'output of', why: 'A team that learns the date beats the tests learns something else too. Nobody can say yet what.' },

    // Branch: velocity targets, a solution that turned out to be an experiment
    {
      id: 'pUnpred',
      kind: 'problem',
      label: 'Delivery unpredictable',
      note: 'nobody can say when',
      parent: 'team',
      relation: 'arises in',
      aka: ['predictability', 'unpredictable'],
      ask: 'Why is delivery so unpredictable?',
      says: 'Inside the team, a problem: nobody can say when anything will be done. Management sets velocity targets, believing that what gets measured gets delivered. The burn-up charts steady. What else the targets do is still a question mark.',
      why: 'Without a forecast, product management can’t promise and sales can’t sell. Predictability is what the people outside the box ask for.',
    },
    {
      id: 'velocity',
      kind: 'solution',
      label: 'Velocity targets',
      strategy: 'contain',
      by: 'management',
      parent: 'pUnpred',
      relation: 'solves',
      aka: ['velocity', 'story points', 'targets', 'metrics'],
      why: 'Management chose velocity targets, believing a number to aim for would make delivery steady. A clear purpose, and an untested one.',
    },
    { id: 'burnup', kind: 'sink', label: 'Steady burn-up charts', valence: 'desired', parent: 'velocity', relation: 'output of', why: 'The targets did what they were chosen for. The charts went up and to the right, sprint after sprint.' },
    {
      id: 'inflation',
      kind: 'sink',
      label: 'Story-point inflation',
      valence: 'undesired',
      condenses: true,
      tracedBy: 'guidance',
      parent: 'velocity',
      relation: 'output of',
      says: 'Then the fog condensed: story-point inflation. Velocity rose every sprint and features didn’t. Product management noticed first, comparing the charts with what actually shipped.',
      why: 'A three-point story became a five. Nobody cheated; everyone estimated a little safer. Nobody named this output at design time; product management traced it, comparing charts with what shipped.',
    },
    { id: 'vUnknown', kind: 'sink', label: '?', valence: 'unknown', parent: 'velocity', relation: 'output of', why: 'Every solution is a hypothesis. The targets had a clear purpose, and outputs nobody had named yet.' },
    {
      id: 'pInflation',
      kind: 'problem',
      label: 'Points mean nothing',
      note: 'traced by product management',
      parent: 'inflation',
      relation: 'arises from',
      says: 'An output nobody could name became one nobody could ignore. Points mean nothing now, so management drops the targets. The dashboards go dark, and the organisation knows something it didn’t.',
      why: 'Once points inflate, the forecast they were meant to give is worse than having none.',
    },
    {
      id: 'dropTargets',
      kind: 'solution',
      label: 'Drop the targets',
      strategy: 'reverse',
      by: 'management',
      parent: 'pInflation',
      relation: 'solves',
      why: 'Sometimes the best solution to a problem is to undo the solution that caused it. Management dropped the targets and kept counting what shipped.',
    },
    { id: 'dark', kind: 'sink', label: 'Dashboards go dark', valence: 'undesired', parent: 'dropTargets', relation: 'output of', why: 'The charts everybody watched are gone. For a while, nobody outside the team knows how it’s doing.' },
    { id: 'lesson', kind: 'sink', label: 'Lesson learned', note: 'a target stops measuring', valence: 'desired', parent: 'dropTargets', relation: 'output of', why: 'When a measure becomes a target, it stops measuring. The experiment failed, and that knowledge is an output too.' },
    { id: 'dUnknown', kind: 'sink', label: '?', valence: 'unknown', parent: 'dropTargets', relation: 'output of', why: 'Undoing a solution is a solution too, with outputs of its own.' },

    // Fog: hypotheses about unknown undesirables
    {
      id: 'h1',
      kind: 'hypothesis',
      label: 'Libraries age into obsolescence',
      pattern: 'Eroding goals',
      parent: 'unknown',
      relation: 'guessed from',
      aka: ['obsolescence', 'upgrades', 'legacy'],
      why: 'Upgrades never beat features for a sprint slot. Each skipped one makes the next bigger, until “legacy” is the accepted state.',
    },
    {
      id: 'h2',
      kind: 'hypothesis',
      label: 'Hotfixes bypass the pipeline',
      pattern: 'Fixes that fail',
      parent: 'unknown',
      relation: 'guessed from',
      aka: ['hotfix', 'hotfixes'],
      why: 'An urgent fix skips the tests to reach customers faster, and ships the next bug with it.',
    },
    {
      id: 'h3',
      kind: 'hypothesis',
      label: 'Product and teams blame each other',
      pattern: 'Accidental adversaries',
      parent: 'unknown',
      relation: 'guessed from',
      aka: ['blame'],
      why: 'Dates squeeze the team, shortcuts slip the dates, and each side’s fix makes the other’s problem worse.',
    },
  ],

  inner: [
    ['requests', 'backlog'],
    ['guidance', 'backlog'],
    ['backlog', 'board'],
    ['board', 'build'],
    ['people', 'build'],
    ['libs', 'build'],
    ['build', 'tests'],
    ['tests', 'backlog', 'undesired'],
    ['tests', 'release'],
    ['tools', 'release'],
    ['release', 'ops'],
    ['release', 'features', 'desired'],
    ['ops', 'service', 'desired'],
    ['release', 'bugs', 'undesired'],
    ['build', 'debt', 'undesired'],
  ],

  tour: ['pBugs', 'pDate', 'fog', 'pUnpred'],
})
