// The dairy farm again, written as statements and run on derive(). The golden
// version (../dairy) is laid out and scripted by hand; this one keeps its words
// and adds the few finishing touches derive() accepts (part positions, branch
// nudges, revisit lines, a prelude, boundary order, keyword intents), so the two
// can be held side by side. Where they still differ, the engine decides.

import { derive } from '../../scene/derive'

export const dairyDerived = derive({
  id: 'dairy-derived',
  title: 'Dairy farm (derived)',
  goal: 'make a living from milk',
  who: 'the farm',
  intro: 'A dairy farm, as a black box. Things go in, things come out. Some are wanted, some aren’t, and some of them we can’t name yet.',
  inside:
    'Inside, the box is just more boxes. Every flow that crossed the boundary still lands somewhere; nothing appears or vanishes at the edge. And look at the loop: manure feeds the fields, the fields feed the herd. Inside the boundary it’s a resource. At the gate it’s a problem.',
  outro: 'Each part of this machine can answer one question: what are you here for? And each answer leaves something behind. That residue is the next problem.',
  chain:
    'Follow any box back and you reach the reason it exists. Cutting the beds open answers the infections, which answer the beds, which answer lame cows, which answer the farm’s purpose: a living from milk.',

  nodes: [
    {
      id: 'farm',
      kind: 'system',
      label: 'Dairy farm',
      note: 'makes a living from milk',
      relation: 'exists to',
      why: 'The farm turns grass, feed and care into milk. Everything else on this canvas exists because of that.',
    },

    // Inputs
    { id: 'water', kind: 'source', label: 'Water', why: 'Water goes in for drinking and for cleaning. It’s cheap enough that nobody counts it, which is exactly why it’s worth drawing.' },
    { id: 'feed', kind: 'source', label: 'Feed', why: 'Bought feed tops up what the farm’s own grass can’t provide. Every kilo carries someone else’s land with it.' },
    { id: 'genetics', kind: 'source', label: 'Genetics', why: 'Genetics arrive as breeding choices. They shape the herd for a decade, long after anyone remembers making them.' },
    { id: 'energy', kind: 'source', label: 'Energy', why: 'Energy runs the milking, the cooling and the pumps. It flows in quietly, and the farm only notices it on the bill.' },
    { id: 'services', kind: 'source', label: 'Vet & contractors', why: 'The vet and the contractors bring skills the farm doesn’t keep in-house. They see many farms, which makes them the first to spot a pattern.' },

    // Outputs
    { id: 'milk', kind: 'sink', label: 'Milk', valence: 'desired', parent: 'farm', relation: 'output of', why: 'Milk is the reason the farm exists. Every other box on this canvas is either feeding it, or cleaning up after it.' },
    { id: 'beef', kind: 'sink', label: 'Beef & calves', valence: 'desired', parent: 'farm', relation: 'output of', why: 'A cow has to calve to give milk, so every litre comes with a calf attached. Beef is the by-product that pays.' },
    { id: 'manure', kind: 'sink', label: 'Manure', valence: 'undesired', parent: 'farm', relation: 'output of', why: 'Manure leaves the herd every day, wanted or not. On the farm’s own fields it’s fertiliser; past what the land can take, it’s a problem waiting for a name.' },
    { id: 'methane', kind: 'sink', label: 'Methane', valence: 'undesired', parent: 'farm', relation: 'output of', prelude: 'Methane leaves the farm unpriced. Nothing inside this boundary makes it the farm’s problem. Something outside would have to: a rule, a price, a norm.', why: 'Methane leaves with every breath the herd takes. It used to leave for free; since the cap, every tonne counts against the farm.' },
    { id: 'runoff', kind: 'sink', label: 'Nitrogen runoff', valence: 'undesired', diffuse: true, parent: 'farm', relation: 'output of', why: 'Runoff is diffuse. It leaves through every field at once, a little at a time. Diffuse outputs are the hardest to solve, and the easiest to leave off the map.' },
    { id: 'unknown', kind: 'sink', label: '?', note: 'not yet known', valence: 'unknown', parent: 'farm', relation: 'output of' },

    // Inside the farm
    { id: 'feeding', kind: 'part', label: 'Feeding', parent: 'farm', relation: 'part of', at: [-82, 28], why: 'Feeding mixes bought feed with the farm’s own grass, so the herd eats what the land can’t fully provide.' },
    { id: 'youngstock', kind: 'part', label: 'Young stock', parent: 'farm', relation: 'part of', at: [-82, -36], why: 'Young stock replaces cows that leave the herd. Genetics come in here, and pay off years later.' },
    { id: 'herd', kind: 'part', label: 'Herd', parent: 'farm', relation: 'part of', at: [-8, -4], why: 'The herd is the conversion engine: feed and water in, milk, calves, manure and methane out.' },
    { id: 'milking', kind: 'part', label: 'Milking', parent: 'farm', relation: 'part of', at: [80, -62], why: 'Milking turns a cow’s output into a product someone will buy. It is the narrowest gate of the farm.' },
    { id: 'storage', kind: 'part', label: 'Manure storage', parent: 'farm', relation: 'part of', at: [78, 34], why: 'Storage holds manure until the fields can take it. It’s a “contain” solution, and it’s been around so long nobody thinks of it as one.' },
    { id: 'fields', kind: 'part', label: 'Fields', parent: 'farm', relation: 'part of', at: [-4, 60], why: 'The fields close the loop: manure in, grass out. They also leak whatever they can’t hold.' },

    // Manure branch
    {
      id: 'pManure',
      kind: 'problem',
      label: 'Manure surplus',
      note: 'more than the land can take',
      parent: 'manure',
      relation: 'arises from',
      why: 'Manure isn’t a problem by nature; the fields want it. It becomes one when there’s more of it than the land can absorb.',
      ask: 'What happens to the manure?',
      says: 'Name an undesirable and it becomes a problem. A problem invites solutions, and each one is a new box with outputs of its own. The digester transforms manure into energy, and it runs on capital. What it leaves behind: leaks, and a question mark.',
      again: 'The manure branch. Two answers to one problem, each leaving different things behind.',
      nudge: [0, -205],
    },
    {
      id: 'digester',
      kind: 'solution',
      label: 'Digester',
      strategy: 'transform',
      parent: 'pManure',
      relation: 'solves',
      why: 'The digester turns surplus manure into energy and a fertiliser that’s easier to handle. It costs capital to build and to keep tight.',
      ask: 'Compare with the digester',
      says: 'Back to the digester. Neither option is clean. The question isn’t which one has no residue, but which residue you can live with, or solve next.',
    },
    {
      id: 'spread',
      kind: 'solution',
      label: 'Spread on land',
      strategy: 'shift',
      parent: 'pManure',
      relation: 'solves',
      why: 'Spreading moves manure off the farm’s books and into the soil. What the soil can’t hold moves on, into groundwater and air.',
      ask: 'Why not spread it on land?',
      says: 'Spreading on land is cheaper. But look at what it leaves: nitrate seeps into groundwater, ammonia drifts off. Both are diffuse. It doesn’t solve the problem so much as move it past the boundary.',
    },
    { id: 'biogas', kind: 'sink', label: 'Biogas', note: 'sold as energy', valence: 'desired', parent: 'digester', relation: 'output of', why: 'Biogas is the digester’s purpose made visible: manure that was a problem leaves as energy someone will pay for.' },
    {
      id: 'capital',
      kind: 'source',
      label: 'Capital & upkeep',
      parent: 'digester',
      relation: 'input of',
      why: 'Capital goes into the digester; it isn’t something the digester leaves behind. Every input a solution needs raises its own question: where does it come from?',
    },
    {
      id: 'pPays',
      kind: 'problem',
      label: 'Doesn’t pay for itself',
      note: 'gas revenue < capital & upkeep',
      parent: 'capital',
      relation: 'arises from',
      why: 'Whether the digester pays is the balance across its boundary: capital and upkeep in, gas revenue out. When the balance tips the wrong way, the input becomes a problem.',
      ask: 'Does the digester pay?',
      says: 'Capital goes into the digester, to build it and to keep it tight. Whether it pays is the balance across its boundary: gas revenue out, capital in. When the balance tips, the input becomes a problem. The state can answer it with a subsidy, a rule designed as a solution: the mirror image of the cap.',
      again: 'The digester’s balance. Capital in, gas out, and a subsidy holding up one side of the scale.',
    },
    {
      id: 'subsidy',
      kind: 'solution',
      label: 'Biogas subsidy',
      strategy: 'shift',
      byRule: true,
      parent: 'pPays',
      relation: 'solves',
      why: 'The subsidy is a rule designed as a solution: the state pays part of the bill because it wants the methane captured. It’s the mirror image of the cap.',
    },
    { id: 'paysOff', kind: 'sink', label: 'Digester pays off', valence: 'desired', parent: 'subsidy', relation: 'output of', why: 'With the subsidy, the balance tips the right way and the digester earns its keep. On paper, the problem is solved.' },
    { id: 'policy', kind: 'sink', label: 'Depends on policy', note: 'until the next election', valence: 'undesired', parent: 'subsidy', relation: 'output of', why: 'The subsidy solves a money problem by borrowing someone else’s decision. When the policy changes, the problem comes back, and the digester is already built.' },
    { id: 'subUnknown', kind: 'sink', label: '?', valence: 'unknown', parent: 'subsidy', relation: 'output of', why: 'A subsidy changes behaviour beyond its target. Who else builds a digester, just because the money is there? Nobody knows yet.' },
    { id: 'digestate', kind: 'sink', label: 'Digestate', valence: 'desired', parent: 'digester', relation: 'output of', why: 'Digestate is what’s left after digestion: the nutrients without most of the smell, easier to dose on the fields. The loop to the land stays intact.' },
    { id: 'leaks', kind: 'sink', label: 'Methane leaks', valence: 'undesired', parent: 'digester', relation: 'output of', why: 'No digester is perfectly tight. A little methane escapes from every seal, so a solution built to capture methane releases some of its own.' },
    { id: 'dUnknown', kind: 'sink', label: '?', valence: 'unknown', parent: 'digester', relation: 'output of', why: 'Even a well-understood machine leaves room for surprise. The question mark stays, because no design names every output.' },
    { id: 'soil', kind: 'sink', label: 'Soil nutrients', valence: 'desired', parent: 'spread', relation: 'output of', why: 'Spread at the right time and rate, manure feeds the soil. This is the loop the fields were made for.' },
    { id: 'nitrate', kind: 'sink', label: 'Nitrate to groundwater', note: 'diffuse', valence: 'undesired', diffuse: true, parent: 'spread', relation: 'output of', why: 'What the crop can’t take up washes down into the groundwater. It leaves a little at a time, from every field, and turns up years later in someone’s drinking water.' },
    { id: 'ammonia', kind: 'sink', label: 'Ammonia to air', note: 'diffuse', valence: 'undesired', diffuse: true, parent: 'spread', relation: 'output of', why: 'Ammonia drifts off the moment manure meets the air. It comes down again on nature that can’t take the extra nitrogen.' },
    { id: 'sUnknown', kind: 'sink', label: '?', valence: 'unknown', parent: 'spread', relation: 'output of', why: 'What decades of spreading do to the soil, nobody can fully say yet. The question mark is honest about it.' },

    // Methane cap branch
    { id: 'warming', kind: 'context', label: 'Climate warming', why: 'Warming is the state’s problem, not the farm’s. Seen from here it’s background, until a rule brings it inside.' },
    {
      id: 'cap',
      kind: 'rule',
      label: 'Methane cap 2030',
      parent: 'warming',
      relation: 'the state’s answer to',
      why: 'The cap is someone else’s solution. For the state it answers warming; for the farm it is a new problem, created on purpose.',
    },
    {
      id: 'pCap',
      kind: 'problem',
      label: 'Methane over cap',
      note: 'made a problem by rule',
      parent: 'methane',
      relation: 'arises from',
      why: 'Methane was always leaving the farm. The cap is what makes it this farm’s problem.',
      pressedBy: 'cap',
      ask: 'What if methane is capped?',
      says: 'A rule arrives. It’s someone else’s solution, the state’s answer to warming, and here it lands as a problem, on purpose. A feed additive cuts methane at the source. It costs money per litre, and what it does long-term is still a question mark.',
      again: 'The methane cap, and what it set in motion.',
      nudge: [0, 153],
    },
    {
      id: 'additive',
      kind: 'solution',
      label: 'Feed additive',
      strategy: 'eliminate',
      parent: 'pCap',
      relation: 'solves',
      why: 'The additive suppresses methane in the rumen, at the source. It works today; what it does over a cow’s lifetime is still a question mark.',
      ask: 'Compare with the additive',
      says: 'The additive again. It keeps the problem here, where it can at least be seen and measured.',
    },
    {
      id: 'fewer',
      kind: 'solution',
      label: 'Fewer cows',
      strategy: 'eliminate',
      parent: 'pCap',
      relation: 'solves',
      why: 'Fewer cows meets the cap on paper. The milk is still drunk somewhere, so production and its methane move abroad.',
      ask: 'Why not keep fewer cows?',
      says: 'Fewer cows meets the cap on paper. But the milk still gets drunk, so production moves abroad, and the methane goes with it. That’s leakage: the problem didn’t go away, it left the boundary. Draw the boundary wider and this solution could be worse than the problem.',
    },
    { id: 'lessCH4', kind: 'sink', label: 'Less methane', valence: 'desired', parent: 'additive', relation: 'output of', why: 'The additive does what it promises: less methane per cow, measured at the source. The cap is met.' },
    { id: 'costL', kind: 'sink', label: 'Cost per litre', valence: 'undesired', parent: 'additive', relation: 'output of', why: 'The additive has to be bought every day, for every cow. Meeting the cap becomes a running cost on every litre.' },
    { id: 'aUnknown', kind: 'sink', label: '?', note: 'long-term effects', valence: 'unknown', parent: 'additive', relation: 'output of', why: 'The additive is new. What it does to the cow, the milk or the soil over many years is still a question mark.' },
    { id: 'lessCH4b', kind: 'sink', label: 'Less methane here', valence: 'desired', parent: 'fewer', relation: 'output of', why: 'Fewer cows, less methane. Here, at least.' },
    { id: 'income', kind: 'sink', label: 'Less milk & income', valence: 'undesired', parent: 'fewer', relation: 'output of', why: 'Fewer cows means less milk, and less milk means less income. The cap is met by shrinking the very thing the farm exists for.' },
    { id: 'leakage', kind: 'sink', label: 'Production moves abroad', note: 'diffuse', valence: 'undesired', diffuse: true, parent: 'fewer', relation: 'output of', why: 'Demand for milk doesn’t shrink with the herd. A farm somewhere else fills the gap, and the methane leaves from there instead.' },
    { id: 'fUnknown', kind: 'sink', label: '?', valence: 'unknown', parent: 'fewer', relation: 'output of', why: 'Shrinking a herd changes more than the numbers: the land, the work, the next generation’s choice to farm. None of it has a name yet.' },

    // Water beds: a solution that turned out to be an experiment
    {
      id: 'pLame',
      kind: 'problem',
      label: 'Lame cows',
      note: 'hard stalls, sore hocks',
      parent: 'farm',
      relation: 'arises in',
      why: 'Cows that lie badly stand too long, and their legs pay for it. Lameness costs milk and makes cows suffer.',
      ask: 'What did the farmer try?',
      says: 'The farmer had an answer for lame cows: heated water beds. Soft, warm, surely a help. But every solution is a hypothesis, and this one comes with an output nobody can name yet.',
      again: 'The water beds: a solution that turned out to be an experiment. It failed, and the farm still came out knowing more than it did.',
    },
    {
      id: 'beds',
      kind: 'solution',
      label: 'Heated water beds',
      strategy: 'eliminate',
      by: 'the farmer',
      parent: 'pLame',
      relation: 'solves',
      why: 'The farmer chose heated water beds, believing they would help: soft and warm, so cows lie longer and their legs recover. A clear purpose, and an untested one.',
    },
    { id: 'rested', kind: 'sink', label: 'Rested cows', valence: 'desired', parent: 'beds', relation: 'output of', why: 'The beds did what they were chosen for. Cows lay longer, and their legs recovered. The intended output arrived, as intended.' },
    {
      id: 'mastitis',
      kind: 'sink',
      label: 'Udder infections',
      valence: 'undesired',
      condenses: true,
      parent: 'beds',
      relation: 'output of',
      why: 'Warm and wet is exactly where bacteria thrive. Nobody named this output at design time; the herd showed it, and the vet traced it back to the beds.',
      tracedBy: 'services',
      says: 'Then the fog condensed. The herd came down with udder infections, and the vet traced them to the beds: warm and wet is exactly where bacteria thrive. The question mark gave up one secret, and kept the rest.',
    },
    { id: 'bUnknown', kind: 'sink', label: '?', valence: 'unknown', parent: 'beds', relation: 'output of', why: 'Every solution is a hypothesis. The beds had a clear purpose, and outputs nobody had named yet. One of them has surfaced; the rest are still fog.' },
    {
      id: 'pMastitis',
      kind: 'problem',
      label: 'Infected udders',
      note: 'traced to the beds by the vet',
      parent: 'mastitis',
      relation: 'arises from',
      why: 'An output nobody could name became one nobody could ignore.',
      says: 'The infections became a problem, and the cheapest solution was to undo the first one. The farmer cut the beds open and took the loss. Lame cows are back on the table, but the farm now knows something it didn’t.',
      nudge: [26, 42],
    },
    {
      id: 'cutOpen',
      kind: 'solution',
      label: 'Cut the beds open',
      strategy: 'reverse',
      by: 'the farmer',
      parent: 'pMastitis',
      relation: 'solves',
      why: 'Sometimes the best solution to a problem is to undo the solution that caused it. The farmer cut every bed open and took the loss.',
    },
    { id: 'losses', kind: 'sink', label: 'Losses accepted', valence: 'undesired', parent: 'cutOpen', relation: 'output of', why: 'The beds were paid for, and now they’re gone. Accepting the loss is part of the solution: the money won’t come back, but the infections stop.' },
    { id: 'lesson', kind: 'sink', label: 'Lesson learned', note: 'warm + wet breeds bacteria', valence: 'desired', parent: 'cutOpen', relation: 'output of', why: 'The experiment failed, and the farm knows something it didn’t: warm and wet breeds bacteria. That knowledge is an output too, and it will shape the next solution.' },
    { id: 'cUnknown', kind: 'sink', label: '?', valence: 'unknown', parent: 'cutOpen', relation: 'output of', why: 'Undoing a solution is a solution too, with outputs of its own. Where cutting the beds open leads, nobody can say yet.' },

    // Fog: hypotheses about unknown undesirables
    {
      id: 'h1',
      kind: 'hypothesis',
      label: 'Efficiency gains grow the herd',
      pattern: 'Rebound · Jevons',
      parent: 'unknown',
      relation: 'guessed from',
      why: 'If each cow gets cheaper to keep, the rational move is more cows. Total manure and methane rise even as each cow improves.',
    },
    {
      id: 'h2',
      kind: 'hypothesis',
      label: 'Bought feed replaces grassland',
      pattern: 'Shifting the burden',
      parent: 'unknown',
      relation: 'guessed from',
      why: 'Imported feed is easier than growing grass. Over time the land, and the skill of farming it, wither, and the farm depends on a supply chain it can’t see.',
    },
    {
      id: 'h3',
      kind: 'hypothesis',
      label: 'Routine antibiotics breed resistance',
      pattern: 'Fixes that fail',
      parent: 'unknown',
      relation: 'guessed from',
      why: 'Preventive treatment keeps the herd healthy this year and makes treatment weaker for everyone later.',
    },
  ],

  inner: [
    ['water', 'herd'],
    ['feed', 'feeding'],
    ['genetics', 'youngstock'],
    ['energy', 'milking'],
    ['services', 'herd', 'neutral', { toSide: 'bottom' }],
    ['feeding', 'herd'],
    ['youngstock', 'herd'],
    ['herd', 'milking', 'desired'],
    ['milking', 'milk', 'desired'],
    ['herd', 'beef', 'desired'],
    ['herd', 'storage'],
    ['storage', 'manure', 'undesired'],
    ['herd', 'methane', 'undesired'],
    ['storage', 'methane', 'undesired'],
    ['storage', 'fields', 'neutral', { fromSide: 'bottom', toSide: 'right' }],
    ['fields', 'feeding', 'desired', { fromSide: 'left', toSide: 'bottom' }],
    ['fields', 'runoff', 'undesired'],
  ],

  boundary: ['energy', 'genetics', 'water', 'feed', 'services', 'milk', 'beef', 'manure', 'methane', 'runoff'],

  intents: [
    [/\bbeds?\b|water ?bed|\bvet\b|lame|udder|mastitis|infect|experiment|farmer|what happened/, 'pLame'],
    [/\bpay|profit|capital|money|subsid|revenue|afford|invest/, 'pPays'],
    [/cap|rule|regulat|law|constraint|limit|policy/, 'pCap'],
    [/manure|dung|slurry/, 'pManure'],
    [/methane|emission|climate/, 'methane'],
    [/runoff|nitrogen|nitrate|water quality/, 'runoff'],
  ],

  tour: ['pManure', 'spread', 'digester', 'pPays', 'methane', 'pCap', 'fewer', 'fog', 'pLame'],
})
